name: wg
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - pytorch-cuda=12.1
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - networkx>=2.6.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - tqdm>=4.62.0
  - pip
  - pip:
    - torch-geometric>=2.2.0
    - torch-scatter
    - torch-sparse
    - pytorch-lightning-bolts==0.3.2
